version: "3"
services:
  atomic-core:
    container_name: atomic-core
    image: dockercompose_atomic-core:latest
    restart: always
    expose:
      - 8545
    environment:
      - ETH_NODE_WS=ws://172.17.0.1:8545/ws;